sudo: false

language: php

php:
  - '7.0'

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - phpdbg -qrr -d 'xdebug.overload_var_dump=0' vendor/bin/phpunit --coverage-text
