# https://openid.stackexchange.com/account/login
openids:
  default:
    username: %username%
    password: %password%
  stackoverflow.com:
    username: %username%
    password: %password%

rooms:
  -
    hostname: chat.stackoverflow.com
    secure: true
    id: 110670
  -
    hostname: chat.stackoverflow.com
    secure: true
    id: 100286

room:
  hostname: chat.stackoverflow.com
  secure: true
  id: 100286

logging:
  level: ALL | DEBUG
  handler: Room11\Jeeves\Log\StdOut
  params:
    #filename: /var/log/jeeves.log

storage:
  admin: Room11\Jeeves\Storage\File\Admin
  ban: Room11\Jeeves\Storage\File\Ban
  plugin: Room11\Jeeves\Storage\File\Plugin

plugins:
  - Room11\Jeeves\Chat\Plugin\Canon
  - Room11\Jeeves\Chat\Plugin\Chuck
  - Room11\Jeeves\Chat\Plugin\CodeFormat
  - Room11\Jeeves\Chat\Plugin\Docs
  - Room11\Jeeves\Chat\Plugin\EvalCode
  - Room11\Jeeves\Chat\Plugin\Giphy
  - Room11\Jeeves\Chat\Plugin\Google
  - Room11\Jeeves\Chat\Plugin\HttpRequester
  - Room11\Jeeves\Chat\Plugin\Imdb
  - Room11\Jeeves\Chat\Plugin\Lick
  - Room11\Jeeves\Chat\Plugin\Man
  - Room11\Jeeves\Chat\Plugin\Mdn
  - Room11\Jeeves\Chat\Plugin\Packagist
  - Room11\Jeeves\Chat\Plugin\PHPSrcGrok
  - Room11\Jeeves\Chat\Plugin\Rebecca
  - Room11\Jeeves\Chat\Plugin\Regex
  - Room11\Jeeves\Chat\Plugin\RFC
  - Room11\Jeeves\Chat\Plugin\SwordFight
  - Room11\Jeeves\Chat\Plugin\Tweet
  - Room11\Jeeves\Chat\Plugin\Urban
  - Room11\Jeeves\Chat\Plugin\Wikipedia
  - Room11\Jeeves\Chat\Plugin\Wotd
  - Room11\Jeeves\Chat\Plugin\Xkcd

twitter:
  consumerKey: YourConsumerKey
  consumerSecret: YourConsumerSecret
  accessToken: YourAccessToken
  accessTokenSecret: YourTokenSecret

bitly:
  accessToken: YourBitlyAccessToken
