# https://openid.stackexchange.com/account/login
openids:
  default:
    username: %username%
    password: %password%
  stackoverflow.com:
    username: %username%
    password: %password%

rooms:
  -
    hostname: chat.stackoverflow.com
    secure: true
    id: 110670
  -
    hostname: chat.stackoverflow.com
    secure: true
    id: 100286

room:
  hostname: chat.stackoverflow.com
  secure: true
  id: 100286

logging:
  level: ALL | DEBUG
  handler: Room11\Jeeves\Log\StdOut

storage:
  admin: Room11\Jeeves\Storage\File\Admin
  ban: Room11\Jeeves\Storage\File\Ban

twitter:
  consumerKey: YourConsumerKey
  consumerSecret: YourConsumerSecret
  accessToken: YourAccessToken
  accessTokenSecret: YourTokenSecret

bitly:
  accessToken: YourBitlyAccessToken
